//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Console.BrisaTypeService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ServerUrl/Types/FunctionName", ConfigurationName="BrisaTypeService.TypesSoap")]
    public interface TypesSoap {
        
        // CODEGEN: Generating message contract since element name GetCountriesResult from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/GetCountries", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.GetCountriesResponse GetCountries(global::Test.Console.BrisaTypeService.GetCountriesRequest request);
        
        // CODEGEN: Generating message contract since element name xmlCity from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/GetCities", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.GetCitiesResponse GetCities(global::Test.Console.BrisaTypeService.GetCitiesRequest request);
        
        // CODEGEN: Generating message contract since element name xmlCounties from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/GetDistricts", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.GetDistrictsResponse GetDistricts(global::Test.Console.BrisaTypeService.GetDistrictsRequest request);
        
        // CODEGEN: Generating message contract since element name GetJobsResult from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/GetJobs", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.GetJobsResponse GetJobs(global::Test.Console.BrisaTypeService.GetJobsRequest request);
        
        // CODEGEN: Generating message contract since element name GetApplicationSubjectsResult from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/GetApplicationSubjects", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.GetApplicationSubjectsResponse GetApplicationSubjects(global::Test.Console.BrisaTypeService.GetApplicationSubjectsRequest request);
        
        // CODEGEN: Generating message contract since element name xmlSubject from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/GetApplicationSubSubjects", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsResponse GetApplicationSubSubjects(global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsRequest request);
        
        // CODEGEN: Generating message contract since element name xmlSubSubject from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/GetSubjectDetails", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.GetSubjectDetailsResponse GetSubjectDetails(global::Test.Console.BrisaTypeService.GetSubjectDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name GetProductGroupsResult from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/GetProductGroups", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.GetProductGroupsResponse GetProductGroups(global::Test.Console.BrisaTypeService.GetProductGroupsRequest request);
        
        // CODEGEN: Generating message contract since element name XmlGetAddresses from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/GetAddresses", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.GetAddressesResponse GetAddresses(global::Test.Console.BrisaTypeService.GetAddressesRequest request);
        
        // CODEGEN: Generating message contract since element name XmlGetRegion from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/getRegion", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.getRegionResponse getRegion(global::Test.Console.BrisaTypeService.getRegionRequest request);
        
        // CODEGEN: Generating message contract since element name XmlGetDealer from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/getRegionDealers", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.getRegionDealersResponse getRegionDealers(global::Test.Console.BrisaTypeService.getRegionDealersRequest request);
        
        // CODEGEN: Generating message contract since element name XmlGetDealer from namespace http://ServerUrl/Types/FunctionName is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ServerUrl/Types/FunctionName/getCountryDealers", ReplyAction="*")]
        global::Test.Console.BrisaTypeService.getCountryDealersResponse getCountryDealers(global::Test.Console.BrisaTypeService.getCountryDealersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountries", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetCountriesRequestBody Body;
        
        public GetCountriesRequest() {
        }
        
        public GetCountriesRequest(global::Test.Console.BrisaTypeService.GetCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCountriesRequestBody {
        
        public GetCountriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetCountriesResponseBody Body;
        
        public GetCountriesResponse() {
        }
        
        public GetCountriesResponse(global::Test.Console.BrisaTypeService.GetCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCountriesResult;
        
        public GetCountriesResponseBody() {
        }
        
        public GetCountriesResponseBody(string GetCountriesResult) {
            this.GetCountriesResult = GetCountriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCities", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetCitiesRequestBody Body;
        
        public GetCitiesRequest() {
        }
        
        public GetCitiesRequest(global::Test.Console.BrisaTypeService.GetCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetCitiesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlCity;
        
        public GetCitiesRequestBody() {
        }
        
        public GetCitiesRequestBody(string xmlCity) {
            this.xmlCity = xmlCity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetCitiesResponseBody Body;
        
        public GetCitiesResponse() {
        }
        
        public GetCitiesResponse(global::Test.Console.BrisaTypeService.GetCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetCitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCitiesResult;
        
        public GetCitiesResponseBody() {
        }
        
        public GetCitiesResponseBody(string GetCitiesResult) {
            this.GetCitiesResult = GetCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistrictsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistricts", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetDistrictsRequestBody Body;
        
        public GetDistrictsRequest() {
        }
        
        public GetDistrictsRequest(global::Test.Console.BrisaTypeService.GetDistrictsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetDistrictsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlCounties;
        
        public GetDistrictsRequestBody() {
        }
        
        public GetDistrictsRequestBody(string xmlCounties) {
            this.xmlCounties = xmlCounties;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDistrictsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDistrictsResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetDistrictsResponseBody Body;
        
        public GetDistrictsResponse() {
        }
        
        public GetDistrictsResponse(global::Test.Console.BrisaTypeService.GetDistrictsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetDistrictsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDistrictsResult;
        
        public GetDistrictsResponseBody() {
        }
        
        public GetDistrictsResponseBody(string GetDistrictsResult) {
            this.GetDistrictsResult = GetDistrictsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJobsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJobs", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetJobsRequestBody Body;
        
        public GetJobsRequest() {
        }
        
        public GetJobsRequest(global::Test.Console.BrisaTypeService.GetJobsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetJobsRequestBody {
        
        public GetJobsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJobsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetJobsResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetJobsResponseBody Body;
        
        public GetJobsResponse() {
        }
        
        public GetJobsResponse(global::Test.Console.BrisaTypeService.GetJobsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetJobsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetJobsResult;
        
        public GetJobsResponseBody() {
        }
        
        public GetJobsResponseBody(string GetJobsResult) {
            this.GetJobsResult = GetJobsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetApplicationSubjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetApplicationSubjects", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetApplicationSubjectsRequestBody Body;
        
        public GetApplicationSubjectsRequest() {
        }
        
        public GetApplicationSubjectsRequest(global::Test.Console.BrisaTypeService.GetApplicationSubjectsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetApplicationSubjectsRequestBody {
        
        public GetApplicationSubjectsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetApplicationSubjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetApplicationSubjectsResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetApplicationSubjectsResponseBody Body;
        
        public GetApplicationSubjectsResponse() {
        }
        
        public GetApplicationSubjectsResponse(global::Test.Console.BrisaTypeService.GetApplicationSubjectsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetApplicationSubjectsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetApplicationSubjectsResult;
        
        public GetApplicationSubjectsResponseBody() {
        }
        
        public GetApplicationSubjectsResponseBody(string GetApplicationSubjectsResult) {
            this.GetApplicationSubjectsResult = GetApplicationSubjectsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetApplicationSubSubjectsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetApplicationSubSubjects", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsRequestBody Body;
        
        public GetApplicationSubSubjectsRequest() {
        }
        
        public GetApplicationSubSubjectsRequest(global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetApplicationSubSubjectsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlSubject;
        
        public GetApplicationSubSubjectsRequestBody() {
        }
        
        public GetApplicationSubSubjectsRequestBody(string xmlSubject) {
            this.xmlSubject = xmlSubject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetApplicationSubSubjectsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetApplicationSubSubjectsResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsResponseBody Body;
        
        public GetApplicationSubSubjectsResponse() {
        }
        
        public GetApplicationSubSubjectsResponse(global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetApplicationSubSubjectsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetApplicationSubSubjectsResult;
        
        public GetApplicationSubSubjectsResponseBody() {
        }
        
        public GetApplicationSubSubjectsResponseBody(string GetApplicationSubSubjectsResult) {
            this.GetApplicationSubSubjectsResult = GetApplicationSubSubjectsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubjectDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubjectDetails", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetSubjectDetailsRequestBody Body;
        
        public GetSubjectDetailsRequest() {
        }
        
        public GetSubjectDetailsRequest(global::Test.Console.BrisaTypeService.GetSubjectDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetSubjectDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlSubSubject;
        
        public GetSubjectDetailsRequestBody() {
        }
        
        public GetSubjectDetailsRequestBody(string xmlSubSubject) {
            this.xmlSubSubject = xmlSubSubject;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubjectDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubjectDetailsResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetSubjectDetailsResponseBody Body;
        
        public GetSubjectDetailsResponse() {
        }
        
        public GetSubjectDetailsResponse(global::Test.Console.BrisaTypeService.GetSubjectDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetSubjectDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSubjectDetailsResult;
        
        public GetSubjectDetailsResponseBody() {
        }
        
        public GetSubjectDetailsResponseBody(string GetSubjectDetailsResult) {
            this.GetSubjectDetailsResult = GetSubjectDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductGroupsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductGroups", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetProductGroupsRequestBody Body;
        
        public GetProductGroupsRequest() {
        }
        
        public GetProductGroupsRequest(global::Test.Console.BrisaTypeService.GetProductGroupsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetProductGroupsRequestBody {
        
        public GetProductGroupsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductGroupsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductGroupsResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetProductGroupsResponseBody Body;
        
        public GetProductGroupsResponse() {
        }
        
        public GetProductGroupsResponse(global::Test.Console.BrisaTypeService.GetProductGroupsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetProductGroupsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetProductGroupsResult;
        
        public GetProductGroupsResponseBody() {
        }
        
        public GetProductGroupsResponseBody(string GetProductGroupsResult) {
            this.GetProductGroupsResult = GetProductGroupsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddresses", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetAddressesRequestBody Body;
        
        public GetAddressesRequest() {
        }
        
        public GetAddressesRequest(global::Test.Console.BrisaTypeService.GetAddressesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetAddressesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlGetAddresses;
        
        public GetAddressesRequestBody() {
        }
        
        public GetAddressesRequestBody(string XmlGetAddresses) {
            this.XmlGetAddresses = XmlGetAddresses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddressesResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.GetAddressesResponseBody Body;
        
        public GetAddressesResponse() {
        }
        
        public GetAddressesResponse(global::Test.Console.BrisaTypeService.GetAddressesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class GetAddressesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAddressesResult;
        
        public GetAddressesResponseBody() {
        }
        
        public GetAddressesResponseBody(string GetAddressesResult) {
            this.GetAddressesResult = GetAddressesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRegion", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.getRegionRequestBody Body;
        
        public getRegionRequest() {
        }
        
        public getRegionRequest(global::Test.Console.BrisaTypeService.getRegionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class getRegionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlGetRegion;
        
        public getRegionRequestBody() {
        }
        
        public getRegionRequestBody(string XmlGetRegion) {
            this.XmlGetRegion = XmlGetRegion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRegionResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.getRegionResponseBody Body;
        
        public getRegionResponse() {
        }
        
        public getRegionResponse(global::Test.Console.BrisaTypeService.getRegionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class getRegionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRegionResult;
        
        public getRegionResponseBody() {
        }
        
        public getRegionResponseBody(string getRegionResult) {
            this.getRegionResult = getRegionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionDealersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRegionDealers", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.getRegionDealersRequestBody Body;
        
        public getRegionDealersRequest() {
        }
        
        public getRegionDealersRequest(global::Test.Console.BrisaTypeService.getRegionDealersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class getRegionDealersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlGetDealer;
        
        public getRegionDealersRequestBody() {
        }
        
        public getRegionDealersRequestBody(string XmlGetDealer) {
            this.XmlGetDealer = XmlGetDealer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getRegionDealersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getRegionDealersResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.getRegionDealersResponseBody Body;
        
        public getRegionDealersResponse() {
        }
        
        public getRegionDealersResponse(global::Test.Console.BrisaTypeService.getRegionDealersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class getRegionDealersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getRegionDealersResult;
        
        public getRegionDealersResponseBody() {
        }
        
        public getRegionDealersResponseBody(string getRegionDealersResult) {
            this.getRegionDealersResult = getRegionDealersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCountryDealersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCountryDealers", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.getCountryDealersRequestBody Body;
        
        public getCountryDealersRequest() {
        }
        
        public getCountryDealersRequest(global::Test.Console.BrisaTypeService.getCountryDealersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class getCountryDealersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string XmlGetDealer;
        
        public getCountryDealersRequestBody() {
        }
        
        public getCountryDealersRequestBody(string XmlGetDealer) {
            this.XmlGetDealer = XmlGetDealer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCountryDealersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCountryDealersResponse", Namespace="http://ServerUrl/Types/FunctionName", Order=0)]
        public global::Test.Console.BrisaTypeService.getCountryDealersResponseBody Body;
        
        public getCountryDealersResponse() {
        }
        
        public getCountryDealersResponse(global::Test.Console.BrisaTypeService.getCountryDealersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ServerUrl/Types/FunctionName")]
    public partial class getCountryDealersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getCountryDealersResult;
        
        public getCountryDealersResponseBody() {
        }
        
        public getCountryDealersResponseBody(string getCountryDealersResult) {
            this.getCountryDealersResult = getCountryDealersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TypesSoapChannel : global::Test.Console.BrisaTypeService.TypesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TypesSoapClient : System.ServiceModel.ClientBase<global::Test.Console.BrisaTypeService.TypesSoap>, global::Test.Console.BrisaTypeService.TypesSoap {
        
        public TypesSoapClient() {
        }
        
        public TypesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TypesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TypesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TypesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.GetCountriesResponse global::Test.Console.BrisaTypeService.TypesSoap.GetCountries(global::Test.Console.BrisaTypeService.GetCountriesRequest request) {
            return base.Channel.GetCountries(request);
        }
        
        public string GetCountries() {
            global::Test.Console.BrisaTypeService.GetCountriesRequest inValue = new global::Test.Console.BrisaTypeService.GetCountriesRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.GetCountriesRequestBody();
            global::Test.Console.BrisaTypeService.GetCountriesResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).GetCountries(inValue);
            return retVal.Body.GetCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.GetCitiesResponse global::Test.Console.BrisaTypeService.TypesSoap.GetCities(global::Test.Console.BrisaTypeService.GetCitiesRequest request) {
            return base.Channel.GetCities(request);
        }
        
        public string GetCities(string xmlCity) {
            global::Test.Console.BrisaTypeService.GetCitiesRequest inValue = new global::Test.Console.BrisaTypeService.GetCitiesRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.GetCitiesRequestBody();
            inValue.Body.xmlCity = xmlCity;
            global::Test.Console.BrisaTypeService.GetCitiesResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).GetCities(inValue);
            return retVal.Body.GetCitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.GetDistrictsResponse global::Test.Console.BrisaTypeService.TypesSoap.GetDistricts(global::Test.Console.BrisaTypeService.GetDistrictsRequest request) {
            return base.Channel.GetDistricts(request);
        }
        
        public string GetDistricts(string xmlCounties) {
            global::Test.Console.BrisaTypeService.GetDistrictsRequest inValue = new global::Test.Console.BrisaTypeService.GetDistrictsRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.GetDistrictsRequestBody();
            inValue.Body.xmlCounties = xmlCounties;
            global::Test.Console.BrisaTypeService.GetDistrictsResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).GetDistricts(inValue);
            return retVal.Body.GetDistrictsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.GetJobsResponse global::Test.Console.BrisaTypeService.TypesSoap.GetJobs(global::Test.Console.BrisaTypeService.GetJobsRequest request) {
            return base.Channel.GetJobs(request);
        }
        
        public string GetJobs() {
            global::Test.Console.BrisaTypeService.GetJobsRequest inValue = new global::Test.Console.BrisaTypeService.GetJobsRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.GetJobsRequestBody();
            global::Test.Console.BrisaTypeService.GetJobsResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).GetJobs(inValue);
            return retVal.Body.GetJobsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.GetApplicationSubjectsResponse global::Test.Console.BrisaTypeService.TypesSoap.GetApplicationSubjects(global::Test.Console.BrisaTypeService.GetApplicationSubjectsRequest request) {
            return base.Channel.GetApplicationSubjects(request);
        }
        
        public string GetApplicationSubjects() {
            global::Test.Console.BrisaTypeService.GetApplicationSubjectsRequest inValue = new global::Test.Console.BrisaTypeService.GetApplicationSubjectsRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.GetApplicationSubjectsRequestBody();
            global::Test.Console.BrisaTypeService.GetApplicationSubjectsResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).GetApplicationSubjects(inValue);
            return retVal.Body.GetApplicationSubjectsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsResponse global::Test.Console.BrisaTypeService.TypesSoap.GetApplicationSubSubjects(global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsRequest request) {
            return base.Channel.GetApplicationSubSubjects(request);
        }
        
        public string GetApplicationSubSubjects(string xmlSubject) {
            global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsRequest inValue = new global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsRequestBody();
            inValue.Body.xmlSubject = xmlSubject;
            global::Test.Console.BrisaTypeService.GetApplicationSubSubjectsResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).GetApplicationSubSubjects(inValue);
            return retVal.Body.GetApplicationSubSubjectsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.GetSubjectDetailsResponse global::Test.Console.BrisaTypeService.TypesSoap.GetSubjectDetails(global::Test.Console.BrisaTypeService.GetSubjectDetailsRequest request) {
            return base.Channel.GetSubjectDetails(request);
        }
        
        public string GetSubjectDetails(string xmlSubSubject) {
            global::Test.Console.BrisaTypeService.GetSubjectDetailsRequest inValue = new global::Test.Console.BrisaTypeService.GetSubjectDetailsRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.GetSubjectDetailsRequestBody();
            inValue.Body.xmlSubSubject = xmlSubSubject;
            global::Test.Console.BrisaTypeService.GetSubjectDetailsResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).GetSubjectDetails(inValue);
            return retVal.Body.GetSubjectDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.GetProductGroupsResponse global::Test.Console.BrisaTypeService.TypesSoap.GetProductGroups(global::Test.Console.BrisaTypeService.GetProductGroupsRequest request) {
            return base.Channel.GetProductGroups(request);
        }
        
        public string GetProductGroups() {
            global::Test.Console.BrisaTypeService.GetProductGroupsRequest inValue = new global::Test.Console.BrisaTypeService.GetProductGroupsRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.GetProductGroupsRequestBody();
            global::Test.Console.BrisaTypeService.GetProductGroupsResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).GetProductGroups(inValue);
            return retVal.Body.GetProductGroupsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.GetAddressesResponse global::Test.Console.BrisaTypeService.TypesSoap.GetAddresses(global::Test.Console.BrisaTypeService.GetAddressesRequest request) {
            return base.Channel.GetAddresses(request);
        }
        
        public string GetAddresses(string XmlGetAddresses) {
            global::Test.Console.BrisaTypeService.GetAddressesRequest inValue = new global::Test.Console.BrisaTypeService.GetAddressesRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.GetAddressesRequestBody();
            inValue.Body.XmlGetAddresses = XmlGetAddresses;
            global::Test.Console.BrisaTypeService.GetAddressesResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).GetAddresses(inValue);
            return retVal.Body.GetAddressesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.getRegionResponse global::Test.Console.BrisaTypeService.TypesSoap.getRegion(global::Test.Console.BrisaTypeService.getRegionRequest request) {
            return base.Channel.getRegion(request);
        }
        
        public string getRegion(string XmlGetRegion) {
            global::Test.Console.BrisaTypeService.getRegionRequest inValue = new global::Test.Console.BrisaTypeService.getRegionRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.getRegionRequestBody();
            inValue.Body.XmlGetRegion = XmlGetRegion;
            global::Test.Console.BrisaTypeService.getRegionResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).getRegion(inValue);
            return retVal.Body.getRegionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.getRegionDealersResponse global::Test.Console.BrisaTypeService.TypesSoap.getRegionDealers(global::Test.Console.BrisaTypeService.getRegionDealersRequest request) {
            return base.Channel.getRegionDealers(request);
        }
        
        public string getRegionDealers(string XmlGetDealer) {
            global::Test.Console.BrisaTypeService.getRegionDealersRequest inValue = new global::Test.Console.BrisaTypeService.getRegionDealersRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.getRegionDealersRequestBody();
            inValue.Body.XmlGetDealer = XmlGetDealer;
            global::Test.Console.BrisaTypeService.getRegionDealersResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).getRegionDealers(inValue);
            return retVal.Body.getRegionDealersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::Test.Console.BrisaTypeService.getCountryDealersResponse global::Test.Console.BrisaTypeService.TypesSoap.getCountryDealers(global::Test.Console.BrisaTypeService.getCountryDealersRequest request) {
            return base.Channel.getCountryDealers(request);
        }
        
        public string getCountryDealers(string XmlGetDealer) {
            global::Test.Console.BrisaTypeService.getCountryDealersRequest inValue = new global::Test.Console.BrisaTypeService.getCountryDealersRequest();
            inValue.Body = new global::Test.Console.BrisaTypeService.getCountryDealersRequestBody();
            inValue.Body.XmlGetDealer = XmlGetDealer;
            global::Test.Console.BrisaTypeService.getCountryDealersResponse retVal = ((global::Test.Console.BrisaTypeService.TypesSoap)(this)).getCountryDealers(inValue);
            return retVal.Body.getCountryDealersResult;
        }
    }
}
